export const responseHeaderNames: string[] = [
  "Content-Type",
  "Content-Length",
  "Content-Encoding",
  "Cache-Control",
  "Location",
  "Retry-After",
  "Set-Cookie",
  "WWW-Authenticate",
  "Age",
  "ETag",
  "Last-Modified",
  "Link",
  "Allow",
  "Server",
  "Vary",
  "Expires",
];

export const contentTypeValues: string[] = [
  "application/json",
  "application/problem+json",
  "application/xml",
  "application/x-www-form-urlencoded",
  "application/octet-stream",
  "application/pdf",
  "text/html",
  "text/plain",
  "text/css",
  "text/javascript",
  "multipart/form-data",
  "image/png",
  "image/jpeg",
];
